[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SL4SH-GW"
authors = [{name = "fkroepfl", email = "fjk@home"}]
dynamic = ["version", "description"]
